### ISSUE TITLE
Custom_Messages.iss

### ISSUE THREAD

**Issue by VictorVG** [processhacker2/processhacker2#11]
I write small update for prevent loss messages

/build/Installer/Custom_Messages.iss Thu Feb 18 05:39:54 +0300 2016
/build/Installer/Custom_Messages.iss commit 97880ce7f6ff87159ce71795f9d939ddb2036a20

en.comp_ExtendedServices      =Extended Services
en.comp_ExtendedTools         =Extended Tools
---en.comp_NetAdapters           =Network Adapters
+++en.comp_hardwaredevices       =Hardware Devices
en.comp_NetworkTools          =Network Tools

Thanks!

**Comment by dmex** [comment]
Post it in your ticket... posting it in the comment section of commits doesn't help.

**Comment by wj32** [comment]
Done in 1199d98e6f0c21ed6d0d7f110c007e150e2ce24e

**Comment by VictorVG** [comment]
Ok! I already too tired and confused. Excuse me...
