### ISSUE TITLE
VS2017: ./plugins/ExtendedNotifications/gntp-send/growl.c::70 - error C1001 than AV in cl.exe

### ISSUE THREAD

**Issue by VictorVG** [processhacker2/processhacker2#110]
If build Git ed0753a6099ff9ddcce6f2c8cba10eae67cdc902 using VS2017 then I have errror that compilation failure occurs in the same place where it occurred and in r404 - in ./processhacker/trunk/plugins/extendednotifications/gntp-send/growl.c string 70 similar to x64 compiler tries to perform a cycle of pseudo-random number generation

```
    For (n = 0; n <count; n++)
           Salt [n] = (randSeed % 255) + 1;
       Salt [n] = 0;
    }
```
  And encountering at the end of the cycle Salt [n] tries to divide this number by this zero (?) Can render a _Salt[n]_ reset outside the loop in order to avoid the next "insights" of the compiler?

**added**

1) AV exist only for AMD64 buld
2) VS2015 don't have problerm on this source file....

**Comment by dmex** [comment]
Fixed https://github.com/processhacker2/processhacker2/commit/e0406b518dc2cbc0454633e32b69b98fa88e2d85
