### ISSUE TITLE
window handles.

### ISSUE THREAD

**Issue by MariasStory** [processhacker2/processhacker2#112]
Can you please incorporate window handles like in spy++.

**Comment by dmex** [comment]
Can you be more specific?

**Comment by MariasStory** [comment]
HWND for open windows not only for files.

**Comment by VictorVG** [comment]
Go to Process tab, menu View -> Windows and see all window list. Also You can find a specific window use Ctrl-K hotkey:

![window explorer](https://cloud.githubusercontent.com/assets/906886/23904510/28c3af58-08d9-11e7-93f3-c6341c67d0f3.png)

Why still produce the essence?

**Comment by dmex** [comment]
You can use the 'View menu > Windows' to see open windows (and search if you're using the nightly builds).

These two features are separate because one is based on the NT object manager and the other is based on CSRSS with both returning different information.
