### ISSUE TITLE
[question] what are all the build dependancies for vs 2017?

### ISSUE THREAD

**Issue by L-a-n-g-o-l-i-e-r-s** [processhacker2/processhacker2#114]
Hi there,

I'm sorry to ask this, but the stuff I've read doesn't elaborate what's needed, it said a couple things, tried to compile in VS community 2017 but unfortunately, there's always something I've left out of installation.

I know windows SDK, Git... etc.

So can you tell me everything that's needed to build PH2 and the extra plugins entirely all together, thanks. 

Didn't have much sleep, hope this makes sense. VS 2017 has complicated things a bit for me since I'm on LTSB, I need to install the windows store to even get VS 2017 to work without a virtual machine: :sob:

**Comment by TETYYS** [comment]
what is your question exactly? just download the whole source code and click build

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
I'm asking precisely what are **all** the dependencies so I know what to install, rather than installing 42ish gigs of VS. :8bal:

Thank you for your time.

**Comment by TETYYS** [comment]
VS was never 42gigs, although im not sure that PH supports VS 2017, VS 2017 is lighter than 2015. I think all you need is C/C++ development toolkit and WDK

**Comment by L-a-n-g-o-l-i-e-r-s** [comment]
An entire full install of VS 2017 Community is around 40-42 gb if I recall correctly, that is the purpose of my question, rather than doing a full install I would like to save space and install only what's necisary to build PH2 and the extra plugins.

PH 2 solution file was re-targeted for VS 2017, it's in the commits. :ear_of_rice:

**Comment by dmex** [comment]
You don't need to install everything... Just the Windows SDK (14393 at least until the next Windows release) and a few other minor things like msbuild.

I'll eventually include a dependency check inside the build tools that you can use to check for missing dependencies.

**Comment by dmex** [comment]
I've rewritten the build system from scratch and fixed a bunch of issues including dependencies... You should now only need to install the following two components: 
* MSBuild
* Windows 10 SDK (10.0.15063.0) for Desktop
or 
* VS 2017 C++ Build Tools: http://landinghub.visualstudio.com/visual-cpp-build-tools

Then run build\build_release.cmd or build\build_debug.cmd to build the project. Please open a new ticket for any issues with the new build system 👍
