### ISSUE TITLE
Feature: Scope to This

### ISSUE THREAD

**Issue by Sidneys1** [processhacker2/processhacker2#115]
Pretty simple, PH2 should be able to scope to the tree of a specific process by right-clicking on it, similar to Visual Studio's 'Scope to this'.

**Comment by dmex** [comment]
I don't like this idea because you can accidently click the menu and it's not at all obvious the lists are filtered.

While it's not as automatic, you can also use the searchbox to 'scope' the view by using the multi-search syntax: "chrome|firefox|svchost"
