### ISSUE TITLE
AV in NetworkTools.dll with an erroneous user action - selecting a connection group and calling the context menu for them.

### ISSUE THREAD

**Issue by VictorVG** [processhacker2/processhacker2#116]
AV in NetworkTools.dll with an erroneous user action - selecting a connection group and calling the context menu for them.

V3.0 (r430) AV occurs in NetworkTools.dll v1.8 for an erroneous user action - selecting a connection group and calling the context menu for them.

I received a message on the [**ru-board forum**]{http://forum.ru-board.com/topic.cgi?forum=5&topic=49036&start=200#18) about the fall of Process Hacker when performing a deliberately incorrect operation:

> Written by **Aroza**, Posted on: 06:17 on 21-03-2017
> 
> Process Hacker v3.0.0.430_RUS on the "Network" tab when you select multiple addresses and click the right mouse button to bring up the context menu, the program simply "crashes". Is it just me?
> 
> Author: **mahtanoronra**, Posted on: 06:37 21-03-2017
> 
> **Aroza**
> me too
> 
> Author: **AKRAV**, Posted on: 10:03 on 21-03-2017
> 
> Aroza, mahtanoronra and on the English assembly 3.0.0.430 from Victor_VG in the same way.

Checked - falls with AV (Access Violation) in NetworkTools.dll, at least OS reports:

> The name of the problem event: APPCRASH
> Application name: ProcessHacker.exe
> Application version: 3.0.0.430
> Module name with error: NetworkTools.dll
> Module version with error: 1.8.0.0
> Exception code: c0000005
> Offset exception: 0000000000002026
> OS version: 6.1.7601.2.1.0.256.1

I sent to the debugger the operation `cmp dword ptr [rbx+1ch],1`, _rbx = 0_ in my opinion, it is incorrectly incorrect. reads one of the operands at 1ch and, in theory, triggers memory protection schemes in the CPU. 

Screenshots and dumps attached.

I think it's worth making a defense against such errors, for example, in the form of performing an operation only for the connection on which the cursor is positioned, if there is none, then for the first message with the output of an erroneous user operation of the type "Calling the context menu for multiple connections is invalid.".

Previously, we have not met with such a mistake of the user, and therefore the question of protection from it did not arise.

Scrinshots:

![0](https://cloud.githubusercontent.com/assets/906886/24142093/9ca27b86-0e36-11e7-9f8f-12945f70fd46.png)

![1](https://cloud.githubusercontent.com/assets/906886/24142095/9ca2ddec-0e36-11e7-9adf-4ba35a4455b5.png)

![2](https://cloud.githubusercontent.com/assets/906886/24142092/9c9f9fce-0e36-11e7-9a64-f068479501d2.png)

![3](https://cloud.githubusercontent.com/assets/906886/24142096/9ca478aa-0e36-11e7-8d93-c59dfac4b43b.png)

![4](https://cloud.githubusercontent.com/assets/906886/24142094/9ca2a408-0e36-11e7-8669-247194484bcc.png)

![5](https://cloud.githubusercontent.com/assets/906886/24142097/9ca630a0-0e36-11e7-8a36-5d363acbaf85.png)

![6](https://cloud.githubusercontent.com/assets/906886/24142098/9cbf6e44-0e36-11e7-9ca1-fddfd65af7e2.png)

![7](https://cloud.githubusercontent.com/assets/906886/24142099/9cc133d2-0e36-11e7-8da2-341c9eb07d98.png)

![8](https://cloud.githubusercontent.com/assets/906886/24142103/9cc6ca40-0e36-11e7-8c3b-d53c64a9906d.png)

![9](https://cloud.githubusercontent.com/assets/906886/24142100/9cc40ab2-0e36-11e7-989a-d7b6db338220.png)

![10](https://cloud.githubusercontent.com/assets/906886/24142101/9cc44dba-0e36-11e7-9716-92af6b0e886d.png)

![11](https://cloud.githubusercontent.com/assets/906886/24142102/9cc78cbe-0e36-11e7-8e5a-3a4fc8f14b17.png)

![threads](https://cloud.githubusercontent.com/assets/906886/24142104/9ce13e7a-0e36-11e7-899e-324274d7a00b.png)

Dump's: [**r430_network_multiplay_selection.zip**](https://github.com/processhacker2/processhacker2/files/857706/r430_network_multiplay_selection.zip)

**Comment by VictorVG** [comment]
Addition - **KLASS** wrote:

Well, on idea it is necessary either, or:
A) remove the ability to select multiple rows in the tab

B) again, for example, the operator had to close several connections at once or copy the data of all those connections, then it would be more logical to leave a selection of several lines, but by calling the context menu "darken" all the items except Copy and Close.

I'm for the second, because selecting a few lines, you could, say, by pressing RMsClik in the Remote address column, copy several different addresses into memory at once, which is quite a useful operation, for example with fine-tuning the firewall for isolate any work group if needed...

**Comment by dmex** [comment]
Fixed

**Comment by VictorVG** [comment]
Big thanks!
