### ISSUE TITLE
high dpi support

### ISSUE THREAD

**Issue by amayra** [processhacker2/processhacker2#119]
i think my issue is some with #69 
there weird scale i dont know who i should blame for that 
 [
![screenshot 28](https://cloud.githubusercontent.com/assets/7657277/24547537/3e4b8490-1608-11e7-9057-28bb3005849a.jpg)
](url)

**Comment by dmex** [comment]
> i dont know who i should blame for that

Me? 😄

I've made some changes that should fix the DPI issues.. Can you please update to the latest nightly build and let me know if the DPI issues are fixed?

You can update using the Help > Check for updates menu or download the new build directly:
https://wj32.org/processhacker/nightly.php
