### ISSUE TITLE
autoscroll button proposal

### ISSUE THREAD

**Issue by chico-depressive** [processhacker2/processhacker2#122]
hi,

please add a button to autoscroll on the side of "find a window and kill" button, that feature should be very useful

**Comment by dmex** [comment]
Do you mean a new button for the "scroll to new processes" option?

**Comment by chico-depressive** [comment]
@dmex there is a button in dbgview.exe(sysinternals tool) called AutoScroll, it simply scrolls the bar when new information is available, I would like to have something like it in process hacker

sometimes we want to check when a new process is created, and we have to keep scrolling down manually, kind of annoying

**Comment by dmex** [comment]
There's already an auto-scroll feature on the main menu > view > scroll to new processes.

I'll update the ticket after I've added the toolbar button...

**Comment by chico-depressive** [comment]
scrolling to created processes might raise undesired behaviour for the user if a service starts a process it would probably scroll up and not down

anyway thanks for log window, I did not know about it

**Comment by dmex** [comment]
👍
