### ISSUE TITLE
Build Problem:	The command "..\build\build_updaterev.bat :VCEnd" exited with code 1.	

### ISSUE THREAD

**Issue by hashim19** [processhacker2/processhacker2#126]
Hi everyone, 
I am new to C/C++. I am trying to run processhacker2 but couldn't make it yet. Here is what I did:
1. I cloned the repository through visual studio 2017
2. Then I build the solution, and I received the following errors. 
Can anyone help me with this ? 
![processhacker1](https://cloud.githubusercontent.com/assets/13851084/25277118/d9c6ca2e-26b6-11e7-94f4-f62d8eb18474.png)

**Comment by dmex** [comment]
checkout a fresh copy of the repository and let me know if it's still broken

**Comment by dmex** [comment]
Fixed

**Comment by hashim19** [comment]
Yes, I checked out a fresh copy from your website and it worked. I think you might need to update your GitHub repository. It does not have makesdk.cmd etc file, which is used to make sdk

**Comment by dmex** [comment]
The makesdk file was replaced with \build\build_sdk.cmd including the previous build system. The problem was caused by the file encoding for some file types during Github repository exports 😄
