### ISSUE TITLE
Question: The r468 build fails with the error in the ProcessHacker.vcxproj project. Is there a problem with the SDK configuration?

### ISSUE THREAD

**Issue by VictorVG** [processhacker2/processhacker2#127]
Question: The r468 build fails with the error in the ProcessHacker.vcxproj project. Is there a problem with the SDK configuration?

2>netprv.obj : error LNK2001: unknown external symbol "_GetExtendedUdpTable@24"
2>netprv.obj : error LNK2001: unknown external symbol "__imp__WSAStartup@8"
2>netprv.obj : error LNK2001: unknown external symbol "__imp__GetNameInfoW@28"
2>netprv.obj : error LNK2001: unknown external symbol "_GetExtendedTcpTable@24"
2>\trunk\bin\Release32\ProcessHacker.exe : fatal error LNK1120: unknown external symbol's: 4
2>Build project "ProcessHacker.vcxproj" failure.
========== Build: success: 3, failure: 1, no changed: 0, skipped: 2 ==========

grep find this ordinals in to lib's: 

_GetExtendedUdpTable@24
_GetExtendedTcpTable@24

[1] .\Microsoft SDKs\Windows\v7.0A\Lib\IPHlpApi.Lib
[2] .\Microsoft SDKs\Windows\v7.1A\Lib\IPHlpApi.Lib
[3] .\Windows Kits\10\Lib\10.0.10240.0\um\x86\iphlpapi.lib
[4] .\Windows Kits\10\Lib\10.0.10586.0\um\x86\iphlpapi.lib
[5] .\Windows Kits\10\Lib\10.0.14393.0\um\x86\iphlpapi.lib
[6] .\Windows Kits\10\Lib\10.0.15063.0\um\x86\iphlpapi.lib
[7] .\Windows Kits\8.1\Lib\winv6.3\um\x86\IPHlpApi.Lib

__imp__WSAStartup@8
__imp__GetNameInfoW@28

[1] .\Microsoft SDKs\Windows\v7.0A\Lib\WS2_32.Lib
[2] .\Microsoft SDKs\Windows\v7.1A\Lib\WS2_32.Lib
[3] .\Windows Kits\10\Lib\10.0.10240.0\um\x86\WS2_32.Lib
[4] .\Windows Kits\10\Lib\10.0.10586.0\um\x86\WS2_32.Lib
[5] .\Windows Kits\10\Lib\10.0.14393.0\um\x86\WS2_32.Lib
[6] .\Windows Kits\10\Lib\10.0.15063.0\um\x86\WS2_32.Lib
[7] .\Windows Kits\8.1\Lib\winv6.3\um\x86\WS2_32.Lib

Maybe it makes sense to just lay in the library project from SDK 7.1A? I honestly got confused and could not come up with a correct solution.

**Comment by dmex** [comment]
Duplicate #126

**Comment by VictorVG** [comment]
I think I realized that I missed it - the project file has not been updated and it looks like I'm on it and I get caught once in r475. Now Kdiff3 on this pair will set to see what to fix.

**Comment by VictorVG** [comment]
Yes, it was my mistake - I did not notice the changes in the project file with fatigue and did not flicker them. So I got a "grenade" :) I fixed ph.vcxproj and everything is OK:

Getting build information ... 3.0.475 (CustomBuildTool: Add build_sdk_rebuild.cmd)
Setting up signature files [SKIPPED] (VirusTotal build key)
Building PH [SUCCESS]
Copying text files [SUCCESS]
Copying signed KPH driver [SUCCESS]
Building SDK headers [SUCCESS]
Setting up public headers [SUCCESS]
Setting up resource headers [SUCCESS]
Setting up plugin lib files [SUCCESS]
Building Plugins [SUCCESS]
Building ExtraPlugins [SUCCESS]
Setting up Wow64 files [SUCCESS]
Create PluginsData dir [SUCCESS]
Copy Terminator driver [SUCCESS]
Building Setup [SUCCESS]
Building Process Hacker SDK [SUCCESS]
Building ProcessHacker Zip [SUCCESS]
Building source tarball "tar.exe": Removing leading `../ 'from member names [SUCCESS]
Generating checksums [SUCCESS]
Update build signatures [SKIPPED] (VirusTotal build key)
Cleaning up ...

Build Time: 1 minute (s), 41 second (s)

Is called "if you want to eat jam - do not catch the flies with flies!" And I hoped for "Maybe!" And honestly got problems. :)
