### ISSUE TITLE
Commit-3924d2847d39e69 -  messsages "Git not installed..." but Git 2.12.2 x64 installed

### ISSUE THREAD

**Issue by VictorVG** [processhacker2/processhacker2#128]
Commit-3924d2847d39e69 -  messsages "Git not installed..." but Git 2.12.2 x64 installed
$.\ProcessHacker\trunk\build\build_sdk.cmd
Git not installed... Exiting.
$ .\ProcessHacker\trunk\build\build_release.cmd
Git not installed... Exiting.
$ .\ProcessHacker\trunk\build\build_debug.cmd
Git not installed... Exiting.
$ .\ProcessHacker\trunk\build\build_updaterev.bat
Git not installed... Exiting. 
:)
CustomBuildTool.exe is used .NET and i386, but OS and Git is 64 bit and WOW64 redirect generated problems... I add symlink for Git.exe - CustomBuildTool.exe also can't find Git. :)

**Comment by VictorVG** [comment]
r474 - some messages "Git not installed... Existing." for all CMD + exception:

Signature of the problem:

  Event name of the problem: CLR20r3
  Signature of problem 01: CustomBuildTool.exe
  Signature of the problem 02: 1.0.0.0
  Signature of the problem 03: 58fa8e6a
  Signature of Problem 04: System
  Signature of the problem 05: 4.6.1590.0
  Signature of the problem 06: 5787eed5
  Signature of the problem 07: 2f32
  Signature of the problem 08: 3f0
  Signature of the problem 09: System.ComponentModel.Win32
  OS version: 6.1.7601.2.1.0.256.1
  Language code: 1049
  Additional Information 1: 0a9e
  Additional information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

An attempt to see what happens in the debugger has ended with an abnormal task termination ...

**Comment by dmex** [comment]
Use ticket #126

**Comment by VictorVG** [comment]
Оk! I was just surprised at first, and after it became clear that this is a "joke" WOW64, well, at the same time I noticed a difference. It seems that fatigue played a cruel joke with me and I did not notice the obvious ...
