### ISSUE TITLE
Hardware Device - Unknown disk section problem on System Information window

### ISSUE THREAD

**Issue by VictorVG** [processhacker2/processhacker2#13]
Russian (original):

Проблема впервые замечена на forum.ru-board.com и проявляется если мы настроили вывод статистики HDD/SSD в окне System Information на одной машине, а после не отключив его в настройках плагина вышли из Process Hacker и запустили его с тем же processhacker.settings.xml на другой машине. 

Для такого диска в окне Systerm Information будет выведено имя секции Unknown disk и исправить ошибку без ручной правки строки processhacker.settings.xml::184 - настройки ProcessHacker.HardwareDevices.DiskList невозможно.

Я вижу такое решение - при старте получить список зарегистрированных в ОС устройств (HDD/SSD/NIC) и если записанного в настройках ProcessHacker.HardwareDevices.NetworkList и ProcessHacker.HardwareDevices.DiskList устройства нет, то автоматически его скрывать как из списка выбора (это уже есть), так и из списка отображаемых секций в окне System Information (это пока не делается).  А там пусть пользователь сам разбирается со своими настройками.

English (translation)

The problem first noticed on forum.ru-board.com manifested if we set the output HDD/SSD statistics in the System Information window on the same machine, and then turn it off in the plugin settings out of Process Hacker and run it with the same processhacker.settings .xml on another machine.

For such a disc Systerm Information window will display the name of the section Unknown disk and fix the problem without manual editing processhacker.settings.xml line::184 - ProcessHacker.HardwareDevices.DiskList impossible to configure.

I see this decision - when you start to get a list of registered OS devices (HDD/SSD/NIC) and if the recorded settings and ProcessHacker.HardwareDevices.NetworkList ProcessHacker.HardwareDevices.DiskList device does not automatically hide it from a selection list (this is there), and from the list displayed in the window sections System Information (this is not yet done). And then let the user himself to deal with its own settings.

Illustration:

**KLASS** (original reporter)

![klass](https://cloud.githubusercontent.com/assets/906886/13305173/787f6a84-db6a-11e5-86ad-c6c0d37bbff9.png)

my test:

![ph_2 38 311](https://cloud.githubusercontent.com/assets/906886/13305145/4627f7ae-db6a-11e5-8d92-2f8bd69d152c.png)

Unknown disk is _Seagate ST32000645NS_ installed only on first workstation, but included on _ProcessHacker.HardwareDevices.DiskList_.

**Comment by dmex** [comment]
> run it with the same processhacker.settings .xml on another machine.

You shouldn't be sharing settings files with multiple machines.

**Comment by wj32** [comment]
I don't agree that settings shouldn't be shared - I think plenty of people use portable settings and this would be pretty annoying. It's a bit hard to deal with this though. How about just hiding "unknown disks" in the sys info window and making sure that they appear in options so the user can remove them?

**Comment by wj32** [comment]
BTW I think what they're saying is that the unknown disk doesn't show up in options. That's the key thing...

**Comment by VictorVG** [comment]
Frankly, and I think in a similar way - the need for the withdrawal of technical information on the device operation typically occurs in the case of a malfunction or when debugging the system, and for normal control of her health enough and summary information about the work of the subsystems. And as an engineer, I see no point in showing the details of the individual components of the system do not have the necessary knowledge to the user.

**Comment by dmex** [comment]
I should have been more clear and said that the plugin itself doesn't support using the settings file on multiple machines.

> How about just hiding "unknown disks" in the sys info window and making sure that they appear in options so the user can remove them?

I've pushed those changes in commit https://github.com/processhacker2/processhacker2/commit/9bd42b5ae80f4a055be8a18a57913ee5bb535351

**Comment by VictorVG** [comment]
I build commit 9bd42b5 (v2.38.0.321) and test it - Ok!. SysInfo window - no Unknown disk section, plug-in settings, Disconnect disk - I see Unknown disk as last list item and can clear check. Big thanks! :+1:
