### ISSUE TITLE
Ribbon support

### ISSUE THREAD

**Issue by ForeverOf14** [processhacker2/processhacker2#141]
Windows Ribbon component (UIRibbon.dll) availables on Windows 7 or higher NTOS Build.

It is good to add ribbon support to make ProcessHacker easier to use.

**Comment by VictorVG** [comment]
In the morgue!

**Comment by dmex** [comment]
You can implement the ribbon using plugins the same way ToolStatus implements the Toolbar... Feel free to make a plugin and I'll add it into the plugin browser.
