### ISSUE TITLE
camas.comodo.com upload doesn't work

### ISSUE THREAD

**Issue by vgturtle127** [processhacker2/processhacker2#145]
Just what the title says.

You get the error here:

![image](https://cloud.githubusercontent.com/assets/3183676/26758177/64fd03e0-489c-11e7-9715-88b2fbcb946a.png)

Maybe they updated their API or something? I tried multiple uploads to this, and it doesn't work.

The website redirects to the new Valkyrie system, which may or may not be entirely different, I'm not sure because I pretty much only use VirusTotal and Jotti.

**Comment by dmex** [comment]
Try the latest nightly build:
https://wj32.org/processhacker/nightly.php

**Comment by vgturtle127** [comment]
@dmex 
It has been removed in nightlies. I'm not sure if that is because it is going to be removed permanently, or if the API changed like I said, or what. The new Valkyrie is here:

https://cit.valkyrie.comodo.com/

**Comment by dmex** [comment]
I have been keeping an eye on Valkyrie but the service is still in it's infancy and their API is non-existent. 

I'll add Valkyrie support eventually once they have some sort of API but for now I've added support for VirusTotal bulk scanning and the nightly builds include new VirusTotal columns for the process, service and modules tabs 😄
