### ISSUE TITLE
Hardware Device - Disk Details button - inaccuracies in the interpretation S.M.A.R.T. attributes

### ISSUE THREAD

**Issue by VictorVG** [processhacker2/processhacker2#15]
PH v2.38.03: HardwareDevices: Re-enable disk details button d675524

I looked like some interpreted S.M.A.R.T. attributes in the plug-in window and I saw the error plugin algorithm: it randomly selects the critical attributes, although they may not be such, but for some attributes used decremental counter that the current alggoritm ignores.

For example, I made a couple of screenshots - windows plug Hardware Device:

![hwdev](https://cloud.githubusercontent.com/assets/906886/13365652/595552a8-dce7-11e5-9b71-00fb2d3e5516.png)

 windows and diagnostic tools HWiNFO64:

![hwinfo64](https://cloud.githubusercontent.com/assets/906886/13365657/6205b2ee-dce7-11e5-8208-1969d61d1e70.png)

 for the same drive (a server-side model Seagate Constellation ES.2).

Possible solutions:

-- I would put attributes polling interval S.M.A.R.T. equal to ten minutes because this interval corresponds approximately to device self-control cycle, and if We submit read command S.M.A.R.T. to complete self-test cycle, the device will display the last stored value attributes, and at sufficiently frequent queries S.M.A.R.T. its capacity will be significantly reduced due to the fact that most (all mass models) drives have only one I/O queue (except for server drives for database and video monitoring and recording systems with several parallel I/O queues) ...

An exception are hermetic zone temperature sensors (C2), shock - G-Sense (B7) and errors on the interface (C7) which are monitored continuously.

Attributes B7, C7 necessarily be controlled, because C7 value greater than zero indicate a defect in the electronics or connection cable, the B7 is positive sign exceeding the allowable shock load, and temperature (C2), it is desirable to control, but it is difficult because field recording format of this attribute depends on the model, and the other attributes of the problems are a sign of the change in time value of 05 attributes and C5 talking about HDD working surface degradation or SSD array and allow to see problems with the mechanics of the attributes 07, 08, 0A. 0B - but if they change for the worse is necessary to sound the alarm.

Other attributes more information, and for their correct interpretation must take into account the specific features of the drive model. And when you commit event "derating" I'd just brought a recommendation that should be diagnosed by a test device manufacturer, and then let the user itself on its result decides.

**Comment by TETYYS** [comment]
Where do you even find that SMART window in PH?

**Comment by VictorVG** [comment]
HardwareDevices: Re-enable disk details button d675524 -> added any HDD/SSD have S.M.A.R.T. -> System Information -> Your disk section -> Details button and just visual compare this window and any hardware diagnostics software can read S.M.A.R.T. , example HWiNFO32/HWiNFO64, AIDA64, Crystal DiskInfo ... This window display S.M.A.R.T. atributes - name, ID, e.t.c. ...

**Comment by dmex** [comment]
> it randomly selects the critical attributes

Is that the only problem?
