### ISSUE TITLE
HardwareDevices - Incorrect volume mount points

### ISSUE THREAD

**Issue by VictorVG** [processhacker2/processhacker2#16]
v2.38.0.3 (Git- d675524)

On same HDD ES.2 (see #15) I have four logical volume (one logical volume is hidded), and DVD-RAM device. On plug-in config and System Information section I see that DVD-RAM visualy mapped as HDD volume - HDD volume is C,D,E , DVD-RAM drive letter is J , but I see label ST32000645NS (C,D,E,J) :) Bug.:)

Sorry, I loss version number then found this problem. Added...

**Comment by dmex** [comment]
What does Task Manager show?

**Comment by VictorVG** [comment]
No, letter "J" is associated for SATA DVD-RAM recorder - Pioneer DVR-221L (DVD±RW, DVD±RW DL, DVD-RAM, CD-R, CD-RW). I don't install any RAM drive. DVD-RAM is special optical disk used direct access to any physical sectors and have up to 100000 rewrite cycles (CD-RW, DVD±RW, BD-RE disk can up to 1000 rewrite cycles and can't have direct access to physical sectors).

**Comment by dmex** [comment]
What does Task Manager show?

**Comment by VictorVG** [comment]
It is natural that no RAM disk system, and in the Disk Manager, he is seen as a separate device CD-ROM0 DVD (I) "no carrier":

![disks](https://cloud.githubusercontent.com/assets/906886/13372884/23c68810-dd68-11e5-8bf8-a91a87e582d4.png)

![ph](https://cloud.githubusercontent.com/assets/906886/13372885/23e0b7d0-dd68-11e5-8293-b1456c99bef5.png)

**Comment by dmex** [comment]
Yeah, you're right. It's a separate device bus that is assigning indexes 0 and 1 and thus this drive letters are getting assigned to the disks at indexes 0 and 1.

I'm not sure how to properly handle those non-disk devices yet.

**Comment by VictorVG** [comment]
And if you use [**GetDriveTypeW()**](https://msdn.microsoft.com/ru-ru/library/windows/desktop/aa364939%28v=vs.85%29.aspx) - It also displays the device type, so we can filter out the CD / DVD and other removable storage devices.

**Comment by dmex** [comment]
> And if you use GetDriveTypeW()

No, it doesn't support devices without a mount path. I already query the type directly from the device chipset but the value wasn't checked.

This should be fixed now: https://github.com/processhacker2/processhacker2/commit/cae14cf44966d74dbfa3700b6904c606b44b8c44

**Comment by VictorVG** [comment]
Excellent! This is something that is necessary, but with S.M.A.R.T. let Troubleshooting Packs understand - these attributes and special units of the PC3000 sometimes read wrong, but to repair the failed HDD with them in most cases succeed (if there are necessary spare parts, otherwise the only manufacturer rescue).

The only visual detail that spoils the overall picture is that when we reduce the size of the window horizontally Details button to the right may overlap invisible field as in the screenshot:

![ph1](https://cloud.githubusercontent.com/assets/906886/13397067/386c10e4-df09-11e5-972d-1c0c2a0ecd13.png)

![ph2](https://cloud.githubusercontent.com/assets/906886/13397066/386babb8-df09-11e5-84e0-c0046086ad54.png)

**Comment by dmex** [comment]
Closing bug since reported issue is fixed.

**Comment by VictorVG** [comment]
Big thanks!
