### ISSUE TITLE
Treenew GDI bug

### ISSUE THREAD

**Issue by dmex** [processhacker2/processhacker2#21]
Treenew is using an incorrect GDI context handle while drawing the selection rectangle.

In the call to CreateDIBSection, it's incorrectly using the HDC returned by CreateCompatibleDC instead of the HDC handle of the window.

Treenew.c, PhTnpDrawSelectionRectangle function, line 5620:
`bitmap = CreateDIBSection(tempDc, (BITMAPINFO *)&header, DIB_RGB_COLORS, &bits, NULL, 0);`

Should be:
`bitmap = CreateDIBSection(hdc, (BITMAPINFO *)&header, DIB_RGB_COLORS, &bits, NULL, 0);`

**Comment by wj32** [comment]
What makes you think this is incorrect? It works perfectly fine.
