### ISSUE TITLE
Add a list of users

### ISSUE THREAD

**Issue by KarenArzumanyan** [processhacker2/processhacker2#27]
I ask to add a list of users like in the system task manager or System Explorer.
With the following features:
- Sign Out;
- Disable;
- Send a message;
- Display the status, session number, session type and other information.

Example:
[http://s011.radikal.ru/i315/1409/d6/c3521b1221c9.png](url)

**Comment by wj32** [comment]
There's a Users menu.

**Comment by KarenArzumanyan** [comment]
I know that the list of users is displayed in the menu.
But this is very not convenient!
It is much more convenient when in a table.
