### ISSUE TITLE
Question - who is? v3.0.0.103

### ISSUE THREAD

**Issue by VictorVG** [processhacker2/processhacker2#36]
Found **KLASS** at [**forum.ru-board.com**](http://forum.ru-board.com/topic.cgi?forum=5&topic=29703&start=3240#14):

![1](https://cloud.githubusercontent.com/assets/906886/14591295/420a84d0-0517-11e6-8643-f71fc77189e8.png)

I checked out at - yes, there is a strange element, including in the Nightly Builds specially downloaded to test the hypothesis of a possible error of my build:

![2](https://cloud.githubusercontent.com/assets/906886/14591329/ce8fd73e-0517-11e6-8c1a-40bab50cad06.png)

Therefore, the question arose what is it?

**Comment by dmex** [comment]
Tried disabling all plugins and any tray icons? I've seen this before but not sure which graph/plugin was causing the issue.

**Comment by VictorVG** [comment]
Aha, I found the condition of its appearance - is physically removed from test pack all plugins, and disabled all a tray icon - does not play

![3](https://cloud.githubusercontent.com/assets/906886/14597034/f9b56bf0-0552-11e6-9534-ad14cf54c6b6.png)

 but when turned on display the CPU load in the tray box appeared:

![4](https://cloud.githubusercontent.com/assets/906886/14597042/0386149a-0553-11e6-96f5-ad1c31be9563.png)

**Comment by VictorVG** [comment]
Additional test - all tray icons disabled, all plugins (SVN + plugins-extra - 27 ch) enabled

**Comment by dmex** [comment]
disabled the process list graphs?

**Comment by VictorVG** [comment]
It appears this is not required since **KLASS** is [**now found another condition**]() when the box disappears and it narrows the range of possible searches:

russian (original)

> если после запуска сабжа выбрать поочередно вкладки Services и Network (или наоборот), то квадратик исчезает.
>  
> _Добавлено:_
>
> Также квадратик исчезает, если структура папок по умолчанию и ничего не отключать, а просто пробежаться по озвученным выше вкладкам, при этом вкладку Disk можно не трогать. В общем какой то гемор с вкладками Services и Network.

translate:

> if after running PH alternately select Network and Service tabs (or vice versa), then the square disappears. 
> 
> _Added: _
> 
> Also, the box disappears if the folder structure by default, and does not turn off and just run through the tabs voiced above, with the Disk tab, you can not touch. So what that the hemorrhagic tabbed Services, and Network.

**Comment by wj32** [comment]
Fixed in 9aa97489b24e97e0111f3b1136922660ef2cce79
