### ISSUE TITLE
bug in peview x64 build when viewing x32 exes

### ISSUE THREAD

**Issue by yossizahn** [processhacker2/processhacker2#41]
The x64 build of peview shows an incorrect 64 bit Image Base when viewing 32bit files.

**Comment by dmex** [comment]
I'll leave the ticket open until @wj32 reviews the merge

**Comment by wj32** [comment]
OK looks good.

**Comment by dmex** [comment]
The latest nightly release includes the merged changes:
https://wj32.org/processhacker/forums/viewtopic.php?f=1&t=2315
