### ISSUE TITLE
Creating service does not work

### ISSUE THREAD

**Issue by HyperCriSiS** [processhacker2/processhacker2#43]
Hi,

when I want to create a service on Windows Server 2012 R2 I get an error:
Unable to create the service: wrong parameter
Started as admin.

What could be the issue?

Thanks,
Hyper

**Comment by wj32** [comment]
Need more details

**Comment by HyperCriSiS** [comment]
What do you need?

**Comment by wj32** [comment]
What parameters are you using

**Comment by VictorVG** [comment]
If you are trying to create a service runs under the account Local System or System, then an error message is expected, because password from the system user accounts, regardless of the privilege level is not known.

**Comment by TETYYS** [comment]
Is there any way to create service under a regular account, @VictorVG ?

**Comment by VictorVG** [comment]
Yes, if use administrative account service started As... , but if the user enters the disadvantaged groups (such as Users, Power Users) is based on current service level objectives that may not be enough to him privileges that are available to this account.

**Comment by dmex** [comment]
Any updates on this? We need the parameters you passed in the runas dialog to reproduce the issue...
