### ISSUE TITLE
Steam

### ISSUE THREAD

**Issue by dmex** [processhacker2/processhacker2#49]
Versions affected: 
2.29
2.28
2.27
2.26

**Comment by TheSqrtMinus1** [comment]
I would love for you guys to fix this, for example, maybe ignore certain steam processes by default, or something of the sort. I had to uninstall PH because it was interfering with Team Fortress 2, and would love to reinstall it if/when it gets fixed.

**Comment by dmex** [comment]
https://wj32.org/processhacker/forums/viewtopic.php?f=24&t=2132

**Comment by TETYYS** [comment]
Is this resolved?

**Comment by dmex** [comment]
No. I'm closing it because I don't want multiple bug reports.
