### ISSUE TITLE
System information window does not remember window state

### ISSUE THREAD

**Issue by klonos** [processhacker2/processhacker2#7]
I always have to maximize it each time I start it.

**Comment by wj32** [comment]
I will try to do this soon.

**Comment by klonos** [comment]
Thanx.

**Comment by wj32** [comment]
Done in 99ce8d4d33390b599c23585fadf299294c584e9d

**Comment by klonos** [comment]
Thanx. I really appreciate the time and energy you spend on this project.

**Comment by klonos** [comment]
Forgot to mention this in the latest 2.38 version changelog.
