### ISSUE TITLE
Feature Request: Show processes architectures on their names

### ISSUE THREAD

**Issue by AxDSan** [processhacker2/processhacker2#71]
I thought this was useful for the general audience using Process Hacker, so I thought of something like this:
![](http://i.imgur.com/Vq8sU9p.png)

Thanks in advance for looking forward into this!

**Comment by klonos** [comment]
You can already see the architecture if you add that column in. As a column, it helps if you want to sort/filter by architecture.

**Comment by dmex** [comment]
You can add the 'Bits' column to show process architecture.

**Comment by AxDSan** [comment]
Thanks for pointing out!

**Comment by MagicAndre1981** [comment]
I need to push this @dmex  . It shows Image 64Bit but you can't know if x64 or ARM64. Taskmanager now has a column for this:

![image](https://user-images.githubusercontent.com/8274816/130322963-14a4a02e-c364-4cad-add7-de547e9ccb97.png)

**Comment by Biswa96** [comment]
That's where my homework comes https://github.com/processhacker/processhacker/pull/922. Task manager uses the kernelbase wrapper of that.

**Comment by AxDSan** [comment]
Super, thanks for working on this! 🎉

**Comment by dmex** [comment]
@MagicAndre1981 

You need to create new issues for these things... commenting in a closed issue that's not related to the problem doesn't help track them.

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981
> 
> You need to create new issues for these things..

done in #955
