### ISSUE TITLE
feature request: add "system information" into a lateral sidebar (but keep possibility to open it separately in new window)

### ISSUE THREAD

**Issue by mailinglists35** [processhacker2/processhacker2#77]
![perfmon suggestions](https://cloud.githubusercontent.com/assets/2054302/20717019/22e54162-b665-11e6-97f6-f73382b9f119.png)

optionally, when i mouse over the "disk" graph, show a pop-up containing: 
- avg disk queue length (how many outstanding i/o are in the queue)
- disk busy (disk use) %
- avg io response time
- avg io size

**Comment by dmex** [comment]
This is already implemented in the HardwareDevices plugin that's included with Process Hacker by default.

You need to add disks using the Hacker menu > plugins > HardwareDevices > options window... From there you can add specific disks and network adapters.

Re-open the system information window and you'll see queue lenght, busy time, response time and other details ;)

**Comment by mailinglists35** [comment]
awesome, thank you.
could you still call it a feature request if i wish i could have system information available as a left or right sidebar, integrated in main window?

**Comment by dmex** [comment]
The graphs on the system information window add an extra 40mb of memory required for startup if they're integrated into the main window.

**Comment by mailinglists35** [comment]
> The graphs on the system information window add an extra 40mb of memory required for startup if they're integrated into the main window.

can you make it to show on demand by pressing a button or something?
thank you!

**Comment by dmex** [comment]
You need to make a separate feature request
