### ISSUE TITLE
Option to have the "System Information" auto-start with the application.

### ISSUE THREAD

**Issue by klonos** [processhacker2/processhacker2#8]
I *always* have to go and start it manually and that's a couple of clicks that it would save me.

Alternatively, can we have it so that it loads as a tab of the main application window + have it auto-focus on start up?

**Comment by VictorVG** [comment]
Sorry, but you at least sometimes read the documentation before asking questions? Especially those that are described there. :)

To make programs run at the Windows startup or user logon there are several ways to officially documented in:

1) copy of the program shortcut in the Startup folder, the Start menu (for all or a particular user);
2) add an entry in the key:

_[HKCU\Software\Microsoft\Windows\CurrentVersion\ Run]_

(Write in this way creates a Process Hacker Setup)

or

_[HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run]_

(If you need to run the program for all users)

3) create a task for its launch event in the scheduler (at Command).

There are other ways, but I am afraid you are using them too much firewood mangled, and therefore I will not name. :)

Well, sometimes the setup should look - and suddenly there, yes you tick in the right place is not set? :)

![ph](https://cloud.githubusercontent.com/assets/906886/13024481/5edcf5f0-d206-11e5-94ca-e7112e40cc85.png

**Comment by dmex** [comment]
@VictorVG 

That's not what he was asking about.

**Comment by VictorVG** [comment]
Apparently I did not exactly understand it. :(

**Comment by klonos** [comment]
> Sorry, but you at least sometimes read the documentation before asking questions?

Apparently you need to read more carefully what other people write before making comments like that.

Also, I was born in 1979 and been around since Commodore 64 and DOS. Just out of curiosity when were you born? ...just asking because it is amusing to see you write extended information about how to get things to start up during Windows and point to registry keys when it was most likely someone from my generation that has wrote the article you wrote about it :smile: ...just saying :laughing:

**Comment by klonos** [comment]
@dmex cheers there my fellow Melbournian!

**Comment by VictorVG** [comment]
But at the time I was busy working with 15VSM5 for metallurgical plants. Debug these machines that did not break from the vibration ball mill - board fell from the basket. I had to put an extra fixture - working. And the change in the iron quarry at -60 with the wind fun. :)

**Comment by klonos** [comment]
:smile: ...as I said "out of curiosity". Fair enough then, but I'm sure you must understand where I come from too. I didn't start using PH or Windows yesterday and "[RTFM](https://en.wikipedia.org/wiki/RTFM)" was indeed invented the year I was born:

> The initialism appeared in print in 1979...

 :smile:

**Comment by TETYYS** [comment]
VictorVG, please do not post any text translated with Google Translator, it's indecipherable.

**Comment by klonos** [comment]
:smile:

**Comment by TETYYS** [comment]
Also, regarding the 'issue', I think this is a fairly simple task to do it yourself, I don't think Process Hacker needs automation for tasks so simple

**Comment by klonos** [comment]
It is a very simple task indeed, but I do it *every single time* I start the application. I repeatedly find myself doing the very same two clicks when I start the application: 1) start the "System Information" window and 2) maximize it (#7).

So, if this was a setting (that was also available in the portable version in its .ini file), it would be less annoying. Imagine having to click for example View -> Refresh automatically each time. A simple task too, but annoying as hell if you had to do it all the time.

**Comment by wj32** [comment]
What is the broader use case here? Why do you want to have the System Information window open all the time?

**Comment by klonos** [comment]
Each time I troubleshoot the local system for a specific issue, I need to quickly switch to an overview in order to see what's going on with the system as the issue occurs. For example, is the CPU or GPU spiking? is the hard drive being thrashed by a process? is the network slow because a process started down/up-loading data? or is the process I just started leaking memory?. Having that window open is only either a click or an ALT+Tab away ...that is with history on the graphs for the past few seconds/minutes too. This helps me a lot to narrow down to specific offending applications.

Hope that makes sense.

**Comment by wj32** [comment]
It might make more sense to have a command line switch that opens up the System Information window. What do you think?

**Comment by klonos** [comment]
Yep, I can live with that. So long that I can pass it on to a desktop shortcut as a parameter.

How about the portable version? Can we have setting saved in a .ini or something, so that this is fired when I troubleshoot customer PCs?

**Comment by wj32** [comment]
Sorry, I'm having a hard time understanding why any significant portion of PH users would want to use an option like that. You can just create a batch file that passes in that command line switch.

**Comment by klonos** [comment]
Fair enough.

**Comment by wj32** [comment]
Done in e0d4d362795dd4564b760bbfa717dba084f978f3.

**Comment by klonos** [comment]
Thanx.
