### ISSUE TITLE
feature request: option to open system information graphs inside PH window on left or right side

### ISSUE THREAD

**Issue by mailinglists35** [processhacker2/processhacker2#81]
as requested in https://github.com/processhacker2/processhacker2/issues/77#issuecomment-264641313 i'm creating new issue

**Comment by mailinglists35** [comment]
to be clear: system information window alone is useful, but sometimes it's difficult to use two windows (one for PH, one for SI). what i'm asking is a user configurable option to choose wether SI opens in its own window or it opens in a short version (graphs only) inside PE as a vertical bar aligned to left or right side of PE window

**Comment by dmex** [comment]
Process Hacker needs to be agile enough to start quickly on machines under heavy load and the initialization for the system information window would add an average ~10 seconds to application startup and at minimum an additional 40mb of memory.

You can copy the system information window code into a plugin that creates a new tab with the same content? The support is already there for plugins to implement that feature.
