### ISSUE TITLE
v3.0.0.285 - lost plugin CommonUtils.dll in to installer. Diff and corrected .iss

### ISSUE THREAD

**Issue by VictorVG** [processhacker2/processhacker2#87]
I found small bug on v3.0.0.285 Nightly Builds - lost plugin CommonUtils.dll in to installer :) and corrct it.

Diff:

```
diff U3 ./trunk/build/installer/Process_Hacker_installer.iss ./Process_Hacker_installer.iss
--- ./trunk/build/installer/Process_Hacker_installer.iss	Wed Jun 29 19:38:14 2016
+++ ./Process_Hacker_installer.iss	Sat Dec 17 18:47:52 2016

@@ -115,6 +115,7 @@
 Name: main;                          Description: {cm:comp_Main_App};              Types: full minimal custom; Flags: fixed
 Name: peview;                        Description: {cm:comp_PE_Viewer};             Types: full minimal custom; Flags: disablenouninstallwarning
 Name: plugins;                       Description: {cm:comp_Plugins};               Types: full custom;         Flags: disablenouninstallwarning
+Name: plugins\cmnutil;               Description: {cm:comp_CommonUtil};            Types: full custom;         Flags: disablenouninstallwarning
 Name: plugins\dotnettools;           Description: {cm:comp_DotNetTools};           Types: full custom;         Flags: disablenouninstallwarning
 Name: plugins\extendednotifications; Description: {cm:comp_ExtendedNotifications}; Types: full custom;         Flags: disablenouninstallwarning
 Name: plugins\extendedservices;      Description: {cm:comp_ExtendedServices};      Types: full custom;         Flags: disablenouninstallwarning
@@ -165,7 +166,8 @@
 
 Source: ..\..\bin\Release32\peview.exe;                           DestDir: {app};         Components: peview;                        Flags: ignoreversion; Check: not Is64BitInstallMode()
 Source: ..\..\bin\Release64\peview.exe;                           DestDir: {app};         Components: peview;                        Flags: ignoreversion; Check: Is64BitInstallMode()
-
+Source: ..\..\bin\Release32\plugins\CommonUtil.dll;               DestDir: {app}\plugins; Components: plugins\cmnutil;               Flags: ignoreversion; Check: not Is64BitInstallMode()
+Source: ..\..\bin\Release64\plugins\CommonUtil.dll;               DestDir: {app}\plugins; Components: plugins\cmnutil;               Flags: ignoreversion; Check: Is64BitInstallMode()
 Source: ..\..\bin\Release32\plugins\DotNetTools.dll;              DestDir: {app}\plugins; Components: plugins\dotnettools;           Flags: ignoreversion; Check: not Is64BitInstallMode()
 Source: ..\..\bin\Release64\plugins\DotNetTools.dll;              DestDir: {app}\plugins; Components: plugins\dotnettools;           Flags: ignoreversion; Check: Is64BitInstallMode()
 Source: ..\..\bin\Release32\plugins\DotNetTools.dll;              DestDir: {app}\x86\plugins; Components: plugins\dotnettools;       Flags: ignoreversion; Check: Is64BitInstallMode()
@@ -219,7 +221,8 @@
 Type: files;      Name: {app}\Help.htm;                              Check: IsUpgrade()
 Type: files;      Name: {app}\peview.exe;                            Check: not IsComponentSelected('peview')                        and IsUpgrade()
 Type: files;      Name: {group}\PE Viewer.lnk;                       Check: not IsComponentSelected('peview')                        and IsUpgrade()
-Type: files;      Name: {app}\plugins\DotNetTools.dll;               Check: not IsComponentSelected('plugins\dotnettools')           and IsUpgrade()
+Type: files;      Name: {app}\plugins\CommonUtil.dll;                Check: not IsComponentSelected('plugins\cmnutil')               and IsUpgrade()
+Type: files;      Name: {app}\plugins\DotNetTools.dll;               Check: not IsComponentSelected('plugins\dotnettools')           and IsUpgrade()
 Type: files;      Name: {app}\plugins\ExtendedNotifications.dll;     Check: not IsComponentSelected('plugins\extendednotifications') and IsUpgrade()
 Type: files;      Name: {app}\plugins\ExtendedServices.dll;          Check: not IsComponentSelected('plugins\extendedservices')      and IsUpgrade()
 Type: files;      Name: {app}\plugins\ExtendedTools.dll;             Check: not IsComponentSelected('plugins\extendedtools')         and IsUpgrade()

diff U3 ./trunk/build/installer/Custom_Messages.iss ./Custom_Messages.iss
--- ./trunk/build/installer/Custom_Messages.iss	Wed Jun 29 19:38:14 2016
+++ ./Custom_Messages.iss	Sat Dec 17 18:49:00 2016

@@ -24,6 +24,7 @@
 en.comp_Main_App              =Main application
 en.comp_PE_Viewer             =PE Viewer
 en.comp_Plugins               =Plugins
+en.comp_CommonUtil            =Common Utils 
 en.comp_DotNetTools           =.NET Tools
 en.comp_ExtendedNotifications =Extended Notifications
 en.comp_ExtendedServices      =Extended Services

```
and corrected files and diff on Zip - [**patch_285.zip**](https://github.com/processhacker2/processhacker2/files/658922/patch_285.zip)

**Comment by dmex** [comment]
I've merged the patch just for the nightly builds.

@XhmikosR 
How do we make the CommonUtil plugin not an optional install? It's a dependency for multiple plugins and probably shouldn't be optional for users to install :P

**Comment by VictorVG** [comment]
Ok! I happened to see it in the assembly of .285 - a plug-like look and there, and there is no record. Well, to fix this accidental trifle difficult. I Made, sent.

**Comment by XhmikosR** [comment]
@dmexx: sorry for not looking into the other stuff either, I had forgotten about them. I'll try to have a look soon.

About this, just add `full minimal custom` in its types if it's a component.

**Comment by XhmikosR** [comment]
Or, IMO we should refactor the other plugins to depend on it.

**Comment by XhmikosR** [comment]
@dmex: the hook that requires a review is annoying. I would remove it personally. I want to merge the 3 ready patches from the installer branch to master and it forces me to open a PR. Just extra steps which aren't needed...

**Comment by dmex** [comment]
@XhmikosR 
Fixed

**Comment by VictorVG** [comment]
```
I Inno Script Studio when I first started it a few .ISS corrected syntax - set the parameters in quotation marks, the minimum OS version stated a little differently - 0,6.1, part of the parameters proposed to change for compatibility with version 5.5.9 that I should, other changes can be attributed to improved code readability. Although it also has a disadvantage - it is visually compresses text and you have to manually generate the column for easy reading.

For myself, I left a couple of options - installer version and compilation date. Just for your convenience - to me it's easier to track the progress of development. I and my NSIS projects such technique I use:
```
!define PRODUCT_NAME "Far UE3"
!define PRODUCT_PUBLISHER "Far Group"
!define PRODUCT_WEB_SITE "http://farmanager.com/"
!define VERSION "3.0"
!define COREVER "3.0.0"
!define PRODUCT_VERSION "${VERSION}.${BUILD}.${SVN}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"
 !define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\far.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
SetCompressor /SOLID lzma
!include "MUI.nsh"
!include "nsProcess.nsh"
!include "Registry.nsh"
!include "StdUtils.nsh"
!define BUILD "4870"
!define IMin "1"
!define IMaj "129"
!define IBld "10"
!define IRev "1"
!define IVar "1"
!define REV "1"
!define SVN "14683"
!define MinSVN "14614"
!define UPD "0"
var lng
var s1
var s2
var s3
!define MUI_ICON "${NSISDIR}\Contrib\Graphics\Icons\far.ico"
!define MUI_LANGDLL_REGISTRY_ROOT "${PRODUCT_UNINST_ROOT_KEY}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "NSIS:Language"
!define MUI_ABORTWARNING
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "Russian"
!insertmacro MUI_RESERVEFILE_INSTALLOPTIONS
Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "farue3-update.exe"
InstallDirRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\App Paths\far.exe" ""
RequestExecutionLevel admin
ShowInstDetails hide
ShowUnInstDetails hide
XPStyle on
BrandingText "${PRODUCT_NAME} (v${VERSION}.${BUILD}, SVN r${SVN}, Mod r${REV}, x86) Update"
VIProductVersion "${VERSION}.${BUILD}.${SVN}"
VIAddVersionKey /LANG=${LANG_ENGLISH} "ProductName" "Far Manager UE3 Update for SVN r${MinSVN} - SVN r${SVN}"
VIAddVersionKey /LANG=${LANG_ENGLISH} "Comments" "File and Archive Manager  (v${VERSION}, x86) for Windows XP/2003/Vista/7/2008/8/8.1/2012."
VIAddVersionKey /LANG=${LANG_ENGLISH} "CompanyName" "Eugene Roshal and Far Group, VictorVG @ VikSoft.Ru"
VIAddVersionKey /LANG=${LANG_ENGLISH} "LegalTrademarks" "Eugene Roshal and Far Group, VictorVG @ VikSoft.Ru"
VIAddVersionKey /LANG=${LANG_ENGLISH} "LegalCopyright" "VictorVG @ VikSoft.Ru, Russia, Moscow. All Right Reserved."
VIAddVersionKey /LANG=${LANG_ENGLISH} "FileDescription" "Compiled at ${__DATE__} on ${__TIME__}."
VIAddVersionKey /LANG=${LANG_ENGLISH} "FileVersion" "${IMin}.${IMaj}.${IBld}.${IRev}-${IVar}"
VIAddVersionKey /LANG=${LANG_ENGLISH} "ProductVersion" "${VERSION}"
VIAddVersionKey /LANG=${LANG_ENGLISH} "InternalName" "farue3upd"
VIAddVersionKey /LANG=${LANG_ENGLISH} "OriginalFilename" "update"
VIAddVersionKey /LANG=${LANG_RUSSIAN} "ProductName" "Far Manager UE3 Update для SVN r${MinSVN} - SVN r${SVN}"
VIAddVersionKey /LANG=${LANG_RUSSIAN} "Comments" "Программа Управления Файлами и Архивами (v${VERSION}, x86) для Windows XP/2003/Vista/7/2008/8/8.1/2012."
VIAddVersionKey /LANG=${LANG_RUSSIAN} "CompanyName" "Евгений Рошал и Группа разработчиков FAR, VictorVG @ VikSoft.Ru"
VIAddVersionKey /LANG=${LANG_RUSSIAN} "LegalTrademarks" "Евгений Рошал и Группа разработчиков FAR, VictorVG @ VikSoft.Ru"
VIAddVersionKey /LANG=${LANG_RUSSIAN} "LegalCopyright" "VictorVG @ VikSoft.Ru, Россия, Москва. Все права защищены."
VIAddVersionKey /LANG=${LANG_RUSSIAN} "FileDescription" "Скомпилирована ${__DATE__} в ${__TIME__}."
VIAddVersionKey /LANG=${LANG_RUSSIAN} "FileVersion" "${IMin}.${IMaj}.${IBld}.${IRev}-${IVar}"
VIAddVersionKey /LANG=${LANG_RUSSIAN} "ProductVersion" "${VERSION}"
VIAddVersionKey /LANG=${LANG_RUSSIAN} "InternalName" "farue3upd"
VIAddVersionKey /LANG=${LANG_RUSSIAN} "OriginalFilename" "update
```
This technique - indication of the time of assembly installer proved useful when searching for errors in large scripts - other scripts written by me, include an tens of thousands of lines of code in which it is easy to make a mistake. For example, in the relative address of the jump - I rarely apply labels. An old habit from the time Assembler IBM S/360.

**Comment by dmex** [comment]
Tested with nightly 3.0.322 setup and fixed :)

**Comment by VictorVG** [comment]
Ok! I run build script and testing new commit.
