### ISSUE TITLE
Add search/filtering for individual tabs.

### ISSUE THREAD

**Issue by klonos** [processhacker2/processhacker2#9]
I very often want to filter the disk activity down to a specific directory/file, but that filter is also applied to the rest of the tabs. Can we perhaps have the current search/filter box be a global one, but also add tab-specific ones? That way one for example could filter the disk activity down to a specific folder while still being able to view the main "Processes" tab.

Thanx for considering.

**Comment by andrevlima** [comment]
This feature is very very usefull, especially for example when you search in network tab for a port and click right to "go to process" it pulls the processes tab but it doesn't appear because the filter is activated making near near impossible to find process by network listenning port
