### ISSUE TITLE
Plug-in Network Tools - Close button not work in to plugin settings dialog

### ISSUE THREAD

**Issue by VictorVG** [processhacker2/processhacker2#92]
Reported by [**KLASS**](http://forum.ru-board.com/topic.cgi?forum=5&topic=29703&start=3900#13) , I check - yes, this issues is exists in to version 3.0.296 up to version 3.0.317 in to Network Tools settings dialog Close button only save new settings, but can't close plug-in setup dialog.

**Comment by dmex** [comment]
Fixed

**Comment by VictorVG** [comment]
Big thanks! I test - plug-in work, on settings dialog issues is resolved.
