### ISSUE TITLE
VirusTotal

### ISSUE THREAD

**Issue by wvxwxvw** [processhacker2/processhacker2#94]
How does the display in the column VirusTotal?
If you need a key VirusTotal API, where its PH must take?

![9a5da79c718d](https://cloud.githubusercontent.com/assets/13194155/21479543/42e89052-cb66-11e6-8ea9-75b45e03efee.jpg)

**Comment by VictorVG** [comment]
More precisely, in the absence of an account and the natural keys VirusTotal column displays a message "VirusTotal disabled". I'm still in my build script it can be switched off because they do not understand exactly how to connect it and where to get the necessary keys API.

**Comment by dmex** [comment]
You need to use an official build of Process Hacker that contains the private key required for the VirusTotal API.

Download the nightly build:
https://wj32.org/processhacker/nightly.php

1. Open the current Process Hacker installation directory.
2. Open the Plugins directory.
3. Extract Plugins\OnlineChecks.dll from the downloaded nightly build into your current plugin directory (step 2). 

or

Get your own private key from VirusTotal 😄

**Comment by VictorVG** [comment]
Ok! My build script I modified use Your latest script - big thanks! I add in to scrip some options like generation file _version_ contain current build version and direct make tarball use tar - is simple then use 7-zip for make .tar, then compress to .tar.gz - _tar -czf tarball source_ is very simle. :)

**Comment by dmex** [comment]
This issue has been fixed in recent nightly builds... You can now compile your own version and it'll work with VirusTotal.
