### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pisetskiy** [processhacker2/processhacker2#95]
Hello, Guys. You wrote very cool program.

I have a question about it. How do you retrieve processes descriptions from system?
What part of your code i should look to know this?

Thank you.
![ps_desc](https://cloud.githubusercontent.com/assets/21170019/21502451/e82ab5d6-cc60-11e6-890d-3f7e293c871a.JPG)

**Comment by dmex** [comment]
GetFileVersionInfo?

https://msdn.microsoft.com/en-us/library/windows/desktop/ms647003.aspx
