### ISSUE TITLE
project files include files which are missing in repository

### ISSUE THREAD

**Issue by MagicAndre1981** [processhacker2/processhacker2#97]
With the help of the extension [Show Missing Files](https://marketplace.visualstudio.com/items?itemName=DavidGardiner.ShowMissingFiles) I see that several files are missing in process hacker and plugin but included in the vcxproj files:

![Image missing files](https://www.dropbox.com/s/afwy5gzdi4q2f7p/PH_missingFiles.png?dl=1)

![Image missing files](https://www.dropbox.com/s/u9emrwsh7smtq1h/PH_plugins_missingFiles.png?dl=1)

Please remove them if they are not really needed.

**Comment by dmex** [comment]
These files are included as part of the build process and there will always be files in the project directory that are not part of the Visual Studio solution file.

That extension was never designed for large projects with multiple solutions and you should disable it before building Process Hacker :confused:
